### ISSUE TITLE
BUG: 突然退出したユーザーが所属していたチャンネルにPRIVMSGを送信するとサーバーが落ちる

### ISSUE THREAD

**Issue by rnakaa** [rnakaa/ft_irc#127]
**Describe the bug**
- Ctrl+Cで突然消えたユーザーが所属していたチャンネルにPRIVMSGコマンドを使用するとサーバーが落ちる

**To Reproduce**
- serverクラスで突然ユーザーが消えたことを検知したら、JOIN 0のようなコマンドを実行する
- 
- 

**Expected behavior**
- 
- 
- 

**Other additional information**
-

**Comment by Yono1112** [comment]
Ctrl+cでクライアントが接続切れた時に、そのクライアントが参加していたチャンネル情報を消していないからです。
なのでQuitコマンドのコードかexitAllChannels関数のコードを使って下さい。
